### ISSUE TITLE
Train/Val/Test 문의

### ISSUE THREAD

**Issue by Beomi** [ZIZUN/korean-malicious-comments-dataset#1]
안녕하세요,
우선 좋은 데이터 제작 감사합니다!

다름이 아니라 성능 비교표를 README에 올려주셨는데요,
해당 데이터 성능 측정을 어떻게 하셨는지 궁금합니다 👍 

본 repo에는 trainset밖에 없어보여서요! 

감사합니다.

**Comment by ZIZUN** [comment]
안녕하세요! 우선 질문주셔서 감사드립니다.

성능 측정은 valid set을 따로 두지않고 train:test - 9500:500 으로 진행했습니다. 
측정은 10번 정도 각 모델에서 파라미터 튜닝하며 테스트 하고 가장 높게 나온 accuracy로 기록하였습니다.

아마 성능 비교표에서 0.2 ~ 0.5 정도 떨어진 성능이 어찌보면 정확하다고 할 수 있을 것 같습니다.

README에 좀 더 정확하게 작성했어야 하는데, 부족한 부분 죄송합니다.

**Comment by ZIZUN** [comment]
train:val - 9500:500 이 되겠네요. test가 아니라  제가 머신러닝 배운지 얼마 되지않아 죄송합니다.. ㅎㅎ !

**Comment by Beomi** [comment]
답변 감사합니다 ;)

val set도 random sampling을 하신게 맞을까요? (수동으로 고르신게 아니라)

**Comment by ZIZUN** [comment]
네 random sampling 적용했습니다 !

**Comment by Beomi** [comment]
넵. 감사합니다 :)

**Comment by Beomi** [comment]
ps. KcBERT 써주셔서 감사합니다 ㅎㅎ
